// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnpOSYcfOtEQLeXIkgABHhqCaDmG4Jq5Y',
    appId: '1:337448949347:web:f37c531997031fd63d0a56',
    messagingSenderId: '337448949347',
    projectId: 'course-hotelio',
    authDomain: 'course-hotelio.firebaseapp.com',
    storageBucket: 'course-hotelio.appspot.com',
    measurementId: 'G-KLP5TY6RHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjp1o2HJPq2wJUvrrmkKknL-Bguvj26I4',
    appId: '1:337448949347:android:ff1c0c4ae8ffbcec3d0a56',
    messagingSenderId: '337448949347',
    projectId: 'course-hotelio',
    storageBucket: 'course-hotelio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw3lguuIHht3lIdv5HPIfmxJv-teyLgdc',
    appId: '1:337448949347:ios:fe0a9f9f7c89a6173d0a56',
    messagingSenderId: '337448949347',
    projectId: 'course-hotelio',
    storageBucket: 'course-hotelio.appspot.com',
    iosClientId: '337448949347-eh1ls09ktrbvtbeussoqt7nhl5538obi.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseHotelio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw3lguuIHht3lIdv5HPIfmxJv-teyLgdc',
    appId: '1:337448949347:ios:fe0a9f9f7c89a6173d0a56',
    messagingSenderId: '337448949347',
    projectId: 'course-hotelio',
    storageBucket: 'course-hotelio.appspot.com',
    iosClientId: '337448949347-eh1ls09ktrbvtbeussoqt7nhl5538obi.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseHotelio',
  );
}
